apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mac-connect.fullname" . }}-config
  labels:
    {{- include "mac-connect.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Values.config.configJson | indent 4 }}
