apiVersion: v1
kind: Service
metadata:
  name: mac-connect-relay
  labels:
    {{- include "mac-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.relay.service.type }}
  selector:
    {{- include "mac-connect.relaySelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.relay.service.port }}
      targetPort: 8081
      name: relay
