apiVersion: v1
kind: Service
metadata:
  name: {{ include "68k-relay.fullname" . }}
  labels:
    {{- include "68k-relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "68k-relay.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      name: relay
