apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-proxy.fullname" . }}-config
  labels:
    {{- include "nginx-proxy.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.config.nginxConf | indent 4 }}
