apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    {{- include "nginx-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 8164
              name: skalholt-ws
            - containerPort: 8166
              name: mac-ws
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-logs
              mountPath: /var/log/nginx
            - name: nginx-tls
              mountPath: /etc/nginx/ssl
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.httpGet.path }}
              port: {{ .Values.probes.readiness.httpGet.port }}
              scheme: {{ .Values.probes.readiness.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            exec:
              command:
                {{- toYaml .Values.probes.liveness.exec.command | nindent 16 }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginx-proxy.fullname" . }}-config
        - name: nginx-logs
          persistentVolumeClaim:
            claimName: {{ include "nginx-proxy.fullname" . }}-logs
        - name: nginx-tls
          secret:
            secretName: {{ .Values.tls.secretName }}
