apiVersion: v1
kind: Service
metadata:
  name: dialtone-aim
  labels:
    {{- include "dialtone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.aim.type }}
  selector:
    {{- include "dialtone.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.aim.port }}
      targetPort: 5191
      nodePort: {{ .Values.service.aim.nodePort }}
      name: aim
