apiVersion: v1
kind: Service
metadata:
  name: dialtone-web
  labels:
    {{- include "dialtone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  selector:
    {{- include "dialtone.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: 5200
      name: web
