apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "68k-web.fullname" . }}-config
  labels:
    {{- include "68k-web.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Values.config.configJson | indent 4 }}
