apiVersion: v1
kind: Service
metadata:
  name: {{ include "68k-web.fullname" . }}
  labels:
    {{- include "68k-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "68k-web.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      name: http
