apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-app.fullname" . }}-frontend-config
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Values.config.indexHtml | indent 4 }}
