apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "demo-app.redisSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
