apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "demo-app.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      nodePort: {{ .Values.frontend.service.nodePort }}
