apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "demo-app.backendSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5678
      nodePort: {{ .Values.backend.service.nodePort }}
