apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
    {{- include "demo-app.redisSelectorLabels" . | nindent 4 }}
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-app.redisSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-app.redisSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
