apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skalholt.fullname" . }}-config
  labels:
    {{- include "skalholt.labels" . | nindent 4 }}
data:
  server.yaml: |
{{ .Values.config.serverYaml | indent 4 }}
