apiVersion: v1
kind: Service
metadata:
  name: skalholt-telnet
  labels:
    {{- include "skalholt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.telnet.type }}
  selector:
    {{- include "skalholt.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.telnet.ports }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .nodePort }}
      name: {{ .name }}
    {{- end }}
