apiVersion: v1
kind: Service
metadata:
  name: skalholt-ws
  labels:
    {{- include "skalholt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.websocket.type }}
  selector:
    {{- include "skalholt.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.websocket.port }}
      targetPort: 8164
      name: websocket
