apiVersion: v1
kind: Service
metadata:
  name: skalholt-http
  labels:
    {{- include "skalholt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  selector:
    {{- include "skalholt.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: 8163
      name: http
