{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netatalk.fullname" . }}-share
  labels:
    {{- include "netatalk.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.share.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.share.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
