apiVersion: v1
kind: Service
metadata:
  name: netatalk
  labels:
    {{- include "netatalk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "netatalk.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 548
      nodePort: {{ .Values.service.nodePort }}
      name: afp
